name: Playwright E2E Tests by Environment

on:
  push:
    branches:
      - develop
      - release/staging
      - release/uat
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ 
        github.ref == 'refs/heads/develop' && vars.DEV_URL || 
        github.ref == 'refs/heads/release/staging' && vars.STAGING_URL || 
        github.ref == 'refs/heads/release/uat' && vars.UAT_URL || 
        'https://default-url.com'
      }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r PythonProject/e2e/requirements.txt
          playwright install --with-deps

      - name: Detect test suite
        id: suite
        run: |
          if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
            echo "suite=dev" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "release/staging" ]]; then
            echo "suite=staging" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "release/uat" ]]; then
            echo "suite=uat" >> $GITHUB_OUTPUT
          else
            echo "suite=dev" >> $GITHUB_OUTPUT
          fi

      - name: Run Playwright Tests
        run: |
          echo "Running tests from PythonProject/e2e/tests/${{ steps.suite.outputs.suite }}"
          pytest PythonProject/e2e/tests/${{ steps.suite.outputs.suite }} \
          --base-url="$BASE_URL" -v

